export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILED = 'FETCH_TASKS_FAILED';
export const FETCH_TASK = 'FETCH_TASK';
export const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS';
export const FETCH_TASK_FAILED = 'FETCH_TASK_FAILED';
export const FETCH_TASKS_COUNT = 'FETCH_TASKS_COUNT';
export const FETCH_TASKS_COUNT_SUCCESS = 'FETCH_TASKS_COUNT_SUCCESS';
export const FETCH_TASKS_COUNT_FAILED = 'FETCH_TASKS_COUNT_FAILED';
export const FETCH_TASKS_BY_USER = 'FETCH_TASKS_BY_ID';
export const FETCH_TASKS_BY_USER_SUCCESS = 'FETCH_TASKS_BY_ID_SUCCESS';
export const FETCH_TASKS_BY_USER_FAILED = 'FETCH_TASKS_BY_ID_FAILED';
export const FETCH_TASK_FORM = 'FETCH_TASK_FORM';
export const FETCH_TASK_LIST = 'FETCH_TASK_LIST';
export const FETCH_TASK_LIST_SUCCESS = 'FETCH_TASK_LIST_SUCCESS';
export const FETCH_TASK_LIST_FAILED = 'FETCH_TASK_LIST_FAILED';
export const SET_SELECTED_TASK = 'SET_SELECTED_TASK';
export const SET_SELECTED_TASK_ID = 'SET_SELECTED_TASK_ID';
export const SET_TASK_LIST_FILTER = 'SET_TASK_LIST_FILTER';
export const CLEAN_SELECTED_TASK = 'CLEAN_SELECTED_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const SET_TABLE_KEY = 'SET_TABLE_KEY';
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
export const EDIT_TASK_MESSAGE = 'EDIT_TASK_MESSAGE';
export const FETCH_TASK_MESSAGE = 'FETCH_TASK_MESSAGE';
export const FETCH_TASK_MESSAGE_SUCCESS = 'FETCH_TASK_MESSAGE_SUCCESS';
export const FETCH_TASK_ASSIGNEE_USER = 'FETCH_TASK_ASSIGNEE_USER';
export const FETCH_TASK_ASSIGNEE_USER_SUCCESS = 'FETCH_TASK_ASSIGNEE_USER_SUCCESS';
export const SET_DETAIL_TASK_KEY = 'SET_DETAIL_TASK_KEY';






