export const FETCH_ORDERS = 'FETCH_ORDERS'; 
export const FETCH_ORDER_BY_ID = 'FETCH_ORDER_BY_ID';
export const FETCH_ENTITY_BY_ID = 'FETCH_ENTITY_BY_ID'; 
export const SEARCH_ORDER = 'SEARCH_ORDER';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDER_BY_ID_SUCCESS = 'FETCH_ORDER_BY_ID_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';
export const FETCH_ENTITY_BY_ID_SUCCESS = 'FETCH_ENTITY_BY_ID_SUCCESS';


