export const FETCH_ORDERS = 'FETCH_ORDERS'; 
export const SEARCH_ORDER = 'SEARCH_ORDER';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';
