export const LOAD_CLIENTS_INDAS = "LOAD_CLIENTS_INDAS";
export const LOAD_CLIENTS_INDAS_SUCCESS = "LOAD_CLIENTS_INDAS_SUCCESS";
export const LOAD_CLIENTS_INDAS_FAILED = "LOAD_CLIENTS_INDAS_FAILED";

export const LOAD_ENTITIES_INDAS = "LOAD_ENTITIES_INDAS";
export const LOAD_ENTITIES_INDAS_SUCCESS = "LOAD_ENTITIES_INDAS_SUCCESS";
export const LOAD_ENTITIES_INDAS_FAILED = "LOAD_ENTITIES_INDAS_FAILED";

export const LOAD_WHOLESALERS_INDAS = "LOAD_WHOLESALERS_INDAS";
export const LOAD_WHOLESALERS_INDAS_SUCCESS = "LOAD_WHOLESALERS_INDAS_SUCCESS";
export const LOAD_WHOLESALERS_INDAS_FAILED = "LOAD_WHOLESALERS_INDAS_FAILED";
export const EDIT_CLIENT_INDAS = "EDIT_CLIENT_INDAS";
export const EDIT_CLIENT_INDAS_SUCCESS = "EDIT_CLIENT_INDAS_SUCCESS";
export const EDIT_CLIENT_INDAS_FAILED = "EDIT_CLIENT_INDAS_FAILED";
export const SET_CURRENT_CLIENT_EMAIL = "SET_CURRENT_CLIENT_EMAIL";