import { createActions } from 'redux-actions';

import {
    LOAD_CLIENTS_INDAS,
    LOAD_CLIENTS_INDAS_SUCCESS,
    LOAD_CLIENTS_INDAS_FAILED,
    LOAD_ENTITIES_INDAS,
    LOAD_ENTITIES_INDAS_FAILED,
    LOAD_ENTITIES_INDAS_SUCCESS,
    LOAD_WHOLESALERS_INDAS,
    LOAD_WHOLESALERS_INDAS_FAILED,
    LOAD_WHOLESALERS_INDAS_SUCCESS,
    EDIT_CLIENT_INDAS,
    EDIT_CLIENT_INDAS_SUCCESS,
    EDIT_CLIENT_INDAS_FAILED,
    SET_CURRENT_CLIENT_EMAIL,
    SEARCH_CLIENT_BY,
    GET_USERS_COUNT,
    GET_USERS_COUNT_SUCCESS,
    GET_USERS_COUNT_FAILED,
} from './actionTypes';

export const {
    loadClientsIndas,
    loadClientsIndasFailed,
    loadClientsIndasSuccess,
    loadEntitiesIndas,
    loadEntitiesIndasFailed,
    loadEntitiesIndasSuccess,
    loadWholesalersIndas,
    loadWholesalersIndasFailed,
    loadWholesalersIndasSuccess,
    editClientIndas,
    editClientIndasSuccess,
    editClientIndasFailed,
    setCurrentClientEmail,
    searchClientBy,
    getUsersCount,
    getUsersCountSuccess,
    getUsersCountFailed,
} = createActions(
    LOAD_CLIENTS_INDAS,
    LOAD_CLIENTS_INDAS_FAILED,
    LOAD_CLIENTS_INDAS_SUCCESS,
    LOAD_ENTITIES_INDAS,
    LOAD_ENTITIES_INDAS_FAILED,
    LOAD_ENTITIES_INDAS_SUCCESS,
    LOAD_WHOLESALERS_INDAS,
    LOAD_WHOLESALERS_INDAS_FAILED,
    LOAD_WHOLESALERS_INDAS_SUCCESS,
    EDIT_CLIENT_INDAS,
    EDIT_CLIENT_INDAS_SUCCESS,
    EDIT_CLIENT_INDAS_FAILED,
    SET_CURRENT_CLIENT_EMAIL,
    SEARCH_CLIENT_BY,
    GET_USERS_COUNT,
    GET_USERS_COUNT_SUCCESS,
    GET_USERS_COUNT_FAILED,
);