version: '3.7'

services:

  sample:
    container_name: web-get-new
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app:cached'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true