export const LOAD_CLIENTES_CBIM = 'LOAD_CLIENTES_CBIM'
export const LOAD_CLIENTES_CBIM_SUCCESS = 'LOAD_CLIENTES_CBIM_SUCCESS'
export const LOAD_CLIENTES_CBIM_FAILED = 'LOAD_CLIENTES_CBIM_FAILED'

export const LOAD_CLIENTE_CBIM_ENTIDADES = 'LOAD_CLIENTE_CBIM_ENTIDADES'
export const LOAD_CLIENTE_CBIM_ENTIDADES_SUCCESS =
	'LOAD_CLIENTE_CBIM_ENTIDADES_SUCCESS'
export const LOAD_CLIENTE_CBIM_ENTIDADES_FAILED =
	'LOAD_CLIENTE_CBIM_ENTIDADES_FAILED'
