export const listaClientesCbim = [
	{
		codcli_cbim: 1015,
		coddelegado: 7120,
		codentidad_cbim: 1015,
		codigo_postal: '41014',
		direccion: 'AV JEREZ, 53 URB JARDINES DE HERCULES LETRA C',
		entidad_email: null,
		entidad_nif: null,
		entidad_telefono: '954689479',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ABASCAL ALONSO, FERNANDO',
		nomentidad_cbim: 'ABASCAL ALONSO, FERNANDO',
		poblacion: 'SEVILLA',
		provincia: 'SEVILLA',
		sanibrick: 'S411010',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1022,
		coddelegado: 7792,
		codentidad_cbim: 1022,
		codigo_postal: '14500',
		direccion: 'AV ESTACION, 31',
		entidad_email: 'farmacia245@cofcordoba.com',
		entidad_nif: null,
		entidad_telefono: '957601124',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ABAURRE MORALES, MATILDE',
		nomentidad_cbim: 'ABAURRE MORALES, MATILDE',
		poblacion: 'PUENTE GENIL',
		provincia: 'CORDOBA',
		sanibrick: 'S140370',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1027,
		coddelegado: 7213,
		codentidad_cbim: 1027,
		codigo_postal: '28036',
		direccion: 'MATEO INURRIA, 9',
		entidad_email: 'abegerfarma@telefonica.net',
		entidad_nif: '01329518A',
		entidad_telefono: '913593959',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ABEGER MONTEAGUDO, AMALIA',
		nomentidad_cbim: 'ABEGER MONTEAGUDO, AMALIA',
		poblacion: 'MADRID',
		provincia: 'MADRID',
		sanibrick: 'S280483',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1036,
		coddelegado: 7228,
		codentidad_cbim: 1036,
		codigo_postal: '28010',
		direccion: 'FUENCARRAL, 114',
		entidad_email: null,
		entidad_nif: null,
		entidad_telefono: '914472374',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ABELLO GALLO, MARIA TERESA',
		nomentidad_cbim: 'ABELLO GALLO, MARIA TERESA',
		poblacion: 'MADRID',
		provincia: 'MADRID',
		sanibrick: 'S280345',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1041,
		coddelegado: 7790,
		codentidad_cbim: 1041,
		codigo_postal: '23001',
		direccion: 'PESCADERIA, 5',
		entidad_email: null,
		entidad_nif: '25910920V',
		entidad_telefono: '953190730',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ABOLAFIA DE LLANOS, ANTONIO',
		nomentidad_cbim: 'ABOLAFIA DE LLANOS, ANTONIO',
		poblacion: 'JAEN',
		provincia: 'JAEN',
		sanibrick: 'S230170',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1060,
		coddelegado: 7228,
		codentidad_cbim: 1060,
		codigo_postal: '28290',
		direccion: 'PASEO ALEMANES, 1',
		entidad_email: 'farmacialasmatas@gmail.com',
		entidad_nif: null,
		entidad_telefono: '916302049',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ALONSO CALLEJA, PEDRO',
		nomentidad_cbim: 'ALONSO CALLEJA, PEDRO',
		poblacion: 'ROZAS DE MADRID',
		provincia: 'MADRID',
		sanibrick: 'S280627',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1065,
		coddelegado: 6056,
		codentidad_cbim: 1065,
		codigo_postal: '01008',
		direccion: 'PINTOR ADRIAN ALDECOA, 7',
		entidad_email: null,
		entidad_nif: null,
		entidad_telefono: '94513531',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ACHAERANDIO DIAZ DE GUEREÑU, BEATRIZ',
		nomentidad_cbim: 'ACHAERANDIO DIAZ DE GUEREÑU, BEATRIZ',
		poblacion: 'VITORIA/GASTEIZ',
		provincia: 'ALAVA',
		sanibrick: 'S010320',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1068,
		coddelegado: 4021,
		codentidad_cbim: 1068,
		codigo_postal: '29780',
		direccion: 'CARLOS MILLON, 4 EDIF MORA',
		entidad_email: 'farmacia_blanca@hotmail.com',
		entidad_nif: '26470916D',
		entidad_telefono: '952521527',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'BLANCA TAMARGO, FRANCISCO JOSE',
		nomentidad_cbim: 'BLANCA TAMARGO, FRANCISCO JOSE',
		poblacion: 'NERJA',
		provincia: 'MALAGA',
		sanibrick: 'S290490',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1069,
		coddelegado: 7203,
		codentidad_cbim: 1069,
		codigo_postal: '38003',
		direccion: 'VIERA Y CLAVIJO, 2',
		entidad_email: 'tufarmaciasantacruz@gmail.com',
		entidad_nif: '42087772A',
		entidad_telefono: '922283037',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ACOSTA CABELLO, MARIA ELSA',
		nomentidad_cbim: 'ACOSTA CABELLO, MARIA ELSA',
		poblacion: 'SANTA CRUZ DE TENERIFE',
		provincia: 'TENERIFE',
		sanibrick: 'S380550',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1071,
		coddelegado: 4026,
		codentidad_cbim: 1071,
		codigo_postal: '18004',
		direccion: 'CAMINO RONDA, 88',
		entidad_email: 'farmaciaacostaferrer@hefagra.es',
		entidad_nif: '24119097d',
		entidad_telefono: '958252579',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ACOSTA FERRER, MERCEDES',
		nomentidad_cbim: 'ACOSTA FERRER, MERCEDES',
		poblacion: 'GRANADA',
		provincia: 'GRANADA',
		sanibrick: 'S180540',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1077,
		coddelegado: 7222,
		codentidad_cbim: 1077,
		codigo_postal: '28009',
		direccion: 'JORGE JUAN, 131',
		entidad_email: null,
		entidad_nif: null,
		entidad_telefono: '915733745',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ACOSTA GOMEZ, JAIME ANTONIO',
		nomentidad_cbim: 'ACOSTA GOMEZ, JAIME ANTONIO',
		poblacion: 'MADRID',
		provincia: 'MADRID',
		sanibrick: 'S281155',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1080,
		coddelegado: 7204,
		codentidad_cbim: 1080,
		codigo_postal: '35411',
		direccion: 'PURISIMA, 37',
		entidad_email: null,
		entidad_nif: null,
		entidad_telefono: '928600129',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ACUÑA GARCIA, ANGELA',
		nomentidad_cbim: 'ACUÑA GARCIA, ANGELA',
		poblacion: 'SANTIDAD BAJA',
		provincia: 'LAS PALMAS',
		sanibrick: 'S350690',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1083,
		coddelegado: 4027,
		codentidad_cbim: 1083,
		codigo_postal: '41005',
		direccion: 'DIVINO REDENTOR, 6',
		entidad_email: null,
		entidad_nif: '28885866M',
		entidad_telefono: '954636198',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ACUÑA, C.B.',
		nomentidad_cbim: 'ACUÑA, C.B.',
		poblacion: 'SEVILLA',
		provincia: 'SEVILLA',
		sanibrick: 'S411050',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1087,
		coddelegado: 4012,
		codentidad_cbim: 1087,
		codigo_postal: '28021',
		direccion: 'PLATA, 14',
		entidad_email: 'j-adanrobles@cofm.es',
		entidad_nif: '23210604Q',
		entidad_telefono: '917977771',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ADAN ROBLES, JUANA',
		nomentidad_cbim: 'ADAN ROBLES, JUANA',
		poblacion: 'MADRID',
		provincia: 'MADRID',
		sanibrick: 'S281092',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1095,
		coddelegado: 7219,
		codentidad_cbim: 1095,
		codigo_postal: '50410',
		direccion: 'BULEVAR DE CUARTE, 9',
		entidad_email: 'farmaciacuarte@hotmail.com',
		entidad_nif: '17683873R',
		entidad_telefono: '976503611',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ADIEGO ARIZA, DIONISIO',
		nomentidad_cbim: 'ADIEGO ARIZA, DIONISIO',
		poblacion: 'CUARTE DE HUERVA',
		provincia: 'ZARAGOZA',
		sanibrick: 'S500220',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1099,
		coddelegado: 6056,
		codentidad_cbim: 1099,
		codigo_postal: '01010',
		direccion: 'IRATI, 2',
		entidad_email: null,
		entidad_nif: null,
		entidad_telefono: '945199120',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ADRIAN SAGARDOY, MARI ANGELES',
		nomentidad_cbim: 'ADRIAN SAGARDOY, MARI ANGELES',
		poblacion: 'VITORIA/GASTEIZ',
		provincia: 'ALAVA',
		sanibrick: 'S010280',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1101,
		coddelegado: 7220,
		codentidad_cbim: 1101,
		codigo_postal: '07500',
		direccion: 'PZ RAMON LLULL, 2-3',
		entidad_email: 'GABRIELADROVER@REDFARMA.ORG',
		entidad_nif: '43011204P',
		entidad_telefono: '971843451',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ADROVER OLIVER, GABRIEL',
		nomentidad_cbim: 'ADROVER OLIVER, GABRIEL',
		poblacion: 'MANACOR',
		provincia: 'BALEARES',
		sanibrick: 'S070760',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1116,
		coddelegado: 7213,
		codentidad_cbim: 1116,
		codigo_postal: '28100',
		direccion: 'MARQUES DE LA VALDAVIA, 41',
		entidad_email: null,
		entidad_nif: '07471423B',
		entidad_telefono: '916611300',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'GARCIA AGUADO, SONIA',
		nomentidad_cbim: 'GARCIA AGUADO, SONIA',
		poblacion: 'ALCOBENDAS',
		provincia: 'MADRID',
		sanibrick: 'S280033',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1125,
		coddelegado: 4081,
		codentidad_cbim: 1125,
		codigo_postal: '11203',
		direccion: 'SANTA MARIA MICAELA, 38',
		entidad_email: null,
		entidad_nif: null,
		entidad_telefono: '956662787',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'AGUADO MAESTRO, SOFIA',
		nomentidad_cbim: 'AGUADO MAESTRO, SOFIA',
		poblacion: 'ALGECIRAS',
		provincia: 'CADIZ',
		sanibrick: 'S110530',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1126,
		coddelegado: 6088,
		codentidad_cbim: 1126,
		codigo_postal: '34003',
		direccion: 'ABETOS, 4',
		entidad_email: null,
		entidad_nif: null,
		entidad_telefono: '979743536',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'AGUADO MARTINEZ DE AZCOITI, MERCEDE',
		nomentidad_cbim: 'AGUADO MARTINEZ DE AZCOITI, MERCEDE',
		poblacion: 'PALENCIA',
		provincia: 'PALENCIA',
		sanibrick: 'S340240',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1137,
		coddelegado: 7792,
		codentidad_cbim: 1137,
		codigo_postal: '14270',
		direccion: 'AV CORREDERA, 22',
		entidad_email: 'cagudo5@hotmail.com',
		entidad_nif: null,
		entidad_telefono: '957140063',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'AGUDO RODRIGO, CARMEN',
		nomentidad_cbim: 'AGUDO RODRIGO, CARMEN',
		poblacion: 'HINOJOSA DEL DUQUE',
		provincia: 'CORDOBA',
		sanibrick: 'S140220',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1139,
		coddelegado: 7792,
		codentidad_cbim: 1139,
		codigo_postal: '14007',
		direccion: 'PLATERO PEDRAJAS, 2',
		entidad_email: 'mercedesagudo@redfarma.org',
		entidad_nif: null,
		entidad_telefono: '957250676',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'AGUDO RODRIGO, MERCEDES',
		nomentidad_cbim: 'AGUDO RODRIGO, MERCEDES',
		poblacion: 'CORDOBA',
		provincia: 'CORDOBA',
		sanibrick: 'S140110',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1149,
		coddelegado: 7777,
		codentidad_cbim: 1149,
		codigo_postal: '08911',
		direccion: 'FRANCESC LAYRET, 83',
		entidad_email: null,
		entidad_nif: '38711568S',
		entidad_telefono: '933895208',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'AGUILAR CALVO, ADELA',
		nomentidad_cbim: 'AGUILAR CALVO, ADELA',
		poblacion: 'BADALONA',
		provincia: 'BARCELONA',
		sanibrick: 'S080033',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1156,
		coddelegado: 4021,
		codentidad_cbim: 1156,
		codigo_postal: '29500',
		direccion: 'AV CERVANTES, 13',
		entidad_email: 'farmaciaguilar@hotmail.es',
		entidad_nif: '30071046H',
		entidad_telefono: '952496542',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'AGUILAR JIMENEZ, MANUEL',
		nomentidad_cbim: 'AGUILAR JIMENEZ, MANUEL',
		poblacion: 'ALORA',
		provincia: 'MALAGA',
		sanibrick: 'S290050',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1161,
		coddelegado: 4022,
		codentidad_cbim: 1161,
		codigo_postal: '29620',
		direccion: 'AV MANANTIALES, 7',
		entidad_email: 'pedidos@farmaciabierta.eu',
		entidad_nif: null,
		entidad_telefono: '952382786',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'AGUILAR REDONDO, RAFAEL CARLOS',
		nomentidad_cbim: 'AGUILAR REDONDO, RAFAEL CARLOS',
		poblacion: 'TORREMOLINOS',
		provincia: 'MALAGA',
		sanibrick: 'S290560',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1163,
		coddelegado: 4046,
		codentidad_cbim: 1163,
		codigo_postal: '08002',
		direccion: 'RAMBLA, 44',
		entidad_email: 'fciamvaguilar@xarxafarma.com',
		entidad_nif: '37702612T',
		entidad_telefono: '933020391',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'AGUILAR PEYRA, MARIA VICTORIA',
		nomentidad_cbim: 'AGUILAR PEYRA, MARIA VICTORIA',
		poblacion: 'BARCELONA',
		provincia: 'BARCELONA',
		sanibrick: 'S080099',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1174,
		coddelegado: 4020,
		codentidad_cbim: 1174,
		codigo_postal: '30009',
		direccion: 'RONDA NORTE, 26',
		entidad_email: 'farmacia_toledo@yahoo.es',
		entidad_nif: '23242318J',
		entidad_telefono: '968295301',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'TOLEDO ROMERO, CESAR',
		nomentidad_cbim: 'TOLEDO ROMERO, CESAR',
		poblacion: 'MURCIA',
		provincia: 'MURCIA',
		sanibrick: 'S300530',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1184,
		coddelegado: 7220,
		codentidad_cbim: 1184,
		codigo_postal: '07008',
		direccion: 'JOSEP DARDER METGE, 24',
		entidad_email: 'c.aguilo.000@gmail.com',
		entidad_nif: '42951264Y',
		entidad_telefono: '971276453',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'AGUILO SOLER, CARMEN',
		nomentidad_cbim: 'AGUILO SOLER, CARMEN',
		poblacion: 'PALMA DE MALLORCA',
		provincia: 'BALEARES',
		sanibrick: 'S070630',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1185,
		coddelegado: 4042,
		codentidad_cbim: 1185,
		codigo_postal: '31001',
		direccion: 'ZAPATERIA, 25',
		entidad_email: null,
		entidad_nif: '15783747C',
		entidad_telefono: '948221897',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'AGUINAGA ROUSTAN, ROBERTO',
		nomentidad_cbim: 'AGUINAGA ROUSTAN, ROBERTO',
		poblacion: 'PAMPLONA/IRUÑA',
		provincia: 'NAVARRA',
		sanibrick: 'S310330',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1198,
		coddelegado: 4019,
		codentidad_cbim: 1198,
		codigo_postal: '03201',
		direccion: 'REINA VICTORIA, 73',
		entidad_email: 'pabloagullo@yahoo.es',
		entidad_nif: '21952257E',
		entidad_telefono: '965444938',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'AGULLO PIÑOL, PABLO',
		nomentidad_cbim: 'AGULLO PIÑOL, PABLO',
		poblacion: 'ELCHE/ELX',
		provincia: 'ALICANTE',
		sanibrick: 'S030930',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1199,
		coddelegado: 7226,
		codentidad_cbim: 1199,
		codigo_postal: '25650',
		direccion: 'PZ PORTAL, 10',
		entidad_email: 'jagusticof@gmail.com',
		entidad_nif: '40888946Y',
		entidad_telefono: '973664160',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'AGUSTI GARRIGO, JOANA',
		nomentidad_cbim: 'AGUSTI GARRIGO, JOANA',
		poblacion: 'ISONA',
		provincia: 'LERIDA',
		sanibrick: 'S250280',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1206,
		coddelegado: 7789,
		codentidad_cbim: 1206,
		codigo_postal: '25244',
		direccion: 'AV PRESIDENT MACIA, 15',
		entidad_email: 'gaiguabella@coflleida.cat',
		entidad_nif: '40866483Z',
		entidad_telefono: '973711253',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'AIGUABELLA ALENTA, MARIA GORETTI',
		nomentidad_cbim: 'AIGUABELLA ALENTA, MARIA GORETTI',
		poblacion: 'FONDARELLA',
		provincia: 'LERIDA',
		sanibrick: 'S250240',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1207,
		coddelegado: 6056,
		codentidad_cbim: 1207,
		codigo_postal: '01400',
		direccion: 'VITORIA, 2 ARETA',
		entidad_email: 'farmaciaais@telefonica.net',
		entidad_nif: '72715266F',
		entidad_telefono: '946721775',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'AIS LARISGOITIA, BEGOÑA',
		nomentidad_cbim: 'AIS LARISGOITIA, BEGOÑA',
		poblacion: 'LAUDIO/LLODIO',
		provincia: 'ALAVA',
		sanibrick: 'S010030',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1214,
		coddelegado: 4042,
		codentidad_cbim: 1214,
		codigo_postal: '31600',
		direccion: 'HILARION ESLAVA, 22',
		entidad_email: null,
		entidad_nif: null,
		entidad_telefono: '948243897',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'AJURIA SOTILLO, MARIA JESUS',
		nomentidad_cbim: 'AJURIA SOTILLO, MARIA JESUS',
		poblacion: 'BURLADA/BURLATA',
		provincia: 'NAVARRA',
		sanibrick: 'S310110',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1216,
		coddelegado: 7789,
		codentidad_cbim: 1216,
		codigo_postal: '17258',
		direccion: 'AV GRECIA, 14',
		entidad_email: 'fciacalaball@xarxafarma.com',
		entidad_nif: '40513864P',
		entidad_telefono: '972750524',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ALABALL RADRESA, CAROLINA',
		nomentidad_cbim: 'ALABALL RADRESA, CAROLINA',
		poblacion: 'ESTARTIT',
		provincia: 'GERONA',
		sanibrick: 'S170350',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1231,
		coddelegado: 7787,
		codentidad_cbim: 1231,
		codigo_postal: '02400',
		direccion: 'GRAN VIA, 10',
		entidad_email: null,
		entidad_nif: '22401883K',
		entidad_telefono: '967301156',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ALARCON GONZALEZ, LUIS',
		nomentidad_cbim: 'ALARCON GONZALEZ, LUIS',
		poblacion: 'HELLIN',
		provincia: 'ALBACETE',
		sanibrick: 'S020220',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1238,
		coddelegado: 7201,
		codentidad_cbim: 1238,
		codigo_postal: '28912',
		direccion: 'SAN NICOLAS, 9',
		entidad_email: 'i.ruiz.002@cofm.es',
		entidad_nif: '52126216M',
		entidad_telefono: '916864753',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'RUIZ ALARMA, INMACULADA',
		nomentidad_cbim: 'RUIZ ALARMA, INMACULADA',
		poblacion: 'LEGANES',
		provincia: 'MADRID',
		sanibrick: 'S281062',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1255,
		coddelegado: 4030,
		codentidad_cbim: 1255,
		codigo_postal: '41620',
		direccion: 'MANUEL ROJAS MARCOS, 36',
		entidad_email: null,
		entidad_nif: null,
		entidad_telefono: '954844248',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ALBARREAL NUÑEZ, MARIA DOLORES',
		nomentidad_cbim: 'ALBARREAL NUÑEZ, MARIA DOLORES',
		poblacion: 'MARCHENA',
		provincia: 'SEVILLA',
		sanibrick: 'S410330',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1263,
		coddelegado: 7791,
		codentidad_cbim: 1263,
		codigo_postal: '48260',
		direccion: 'ZUBIAURRE, 9',
		entidad_email: null,
		entidad_nif: null,
		entidad_telefono: '943170097',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ALBERDI LAMIKIZ, MARIBEL',
		nomentidad_cbim: 'ALBERDI LAMIKIZ, MARIBEL',
		poblacion: 'ERMUA',
		provincia: 'VIZCAYA',
		sanibrick: 'S480350',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1267,
		coddelegado: 7217,
		codentidad_cbim: 1267,
		codigo_postal: '46317',
		direccion: 'CARRETERA, 27',
		entidad_email: null,
		entidad_nif: '73649129R',
		entidad_telefono: '962186235',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ALBERO PARDO, MARIA LUISA',
		nomentidad_cbim: 'ALBERO PARDO, MARIA LUISA',
		poblacion: 'VILLARGORDO DEL CABRIEL',
		provincia: 'VALENCIA',
		sanibrick: 'S460140',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1275,
		coddelegado: 7213,
		codentidad_cbim: 1275,
		codigo_postal: '28039',
		direccion: 'LOPE DE HARO, 10',
		entidad_email: 'analbertos@yahoo.es',
		entidad_nif: '02830773W',
		entidad_telefono: '915791896',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ALBERTOS CONSTAN, FUENSANTA ANA MARIA',
		nomentidad_cbim: 'ALBERTOS CONSTAN, FUENSANTA ANA MARIA',
		poblacion: 'MADRID',
		provincia: 'MADRID',
		sanibrick: 'S280597',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1276,
		coddelegado: 7219,
		codentidad_cbim: 1276,
		codigo_postal: '50520',
		direccion: 'PZ CONSTITUCION, 14',
		entidad_email: 'MARIASALDELRIO@HOTMAIL.COM',
		entidad_nif: '09386954X',
		entidad_telefono: '976858509',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'SAL DEL RIO ARGANZA, MARIA',
		nomentidad_cbim: 'SAL DEL RIO ARGANZA, MARIA',
		poblacion: 'MAGALLON',
		provincia: 'ZARAGOZA',
		sanibrick: 'S500080',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1278,
		coddelegado: 6174,
		codentidad_cbim: 1278,
		codigo_postal: '43580',
		direccion: 'BRUC, 21',
		entidad_email: 'falbiolp@coft.org',
		entidad_nif: '40910363X',
		entidad_telefono: '977489750',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ALBIOL PALLES, FRANCESC EDUARD',
		nomentidad_cbim: 'ALBIOL PALLES, FRANCESC EDUARD',
		poblacion: 'DELTEBRE',
		provincia: 'TARRAGONA',
		sanibrick: 'S430550',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1282,
		coddelegado: 4017,
		codentidad_cbim: 1282,
		codigo_postal: '46009',
		direccion: 'SAN PANCRACIO, 18',
		entidad_email: 'carmenalbors@gmail.com',
		entidad_nif: null,
		entidad_telefono: '963499018',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ALBORS RODRIGO, MARIA DEL CARMEN',
		nomentidad_cbim: 'ALBORS RODRIGO, MARIA DEL CARMEN',
		poblacion: 'VALENCIA',
		provincia: 'VALENCIA',
		sanibrick: 'S460890',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1288,
		coddelegado: 7213,
		codentidad_cbim: 1288,
		codigo_postal: '28701',
		direccion: 'CERVANTES, 11',
		entidad_email: 'candidoalca@hotmail.com',
		entidad_nif: '5599927W',
		entidad_telefono: '916517099',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ALCAIDE BRAVO, CANDIDO',
		nomentidad_cbim: 'ALCAIDE BRAVO, CANDIDO',
		poblacion: 'SAN SEBASTIAN DE LOS REYES',
		provincia: 'MADRID',
		sanibrick: 'S281122',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1290,
		coddelegado: 7792,
		codentidad_cbim: 1290,
		codigo_postal: '14400',
		direccion: 'PASEO HERRADURA, 18',
		entidad_email: 'farmacia.alcaide@hotmail.es',
		entidad_nif: null,
		entidad_telefono: '957131426',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ALCAIDE GARCIA AREVALO, JOSE JUAN',
		nomentidad_cbim: 'ALCAIDE GARCIA AREVALO, JOSE JUAN',
		poblacion: 'POZOBLANCO',
		provincia: 'CORDOBA',
		sanibrick: 'S140340',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1291,
		coddelegado: 7120,
		codentidad_cbim: 1291,
		codigo_postal: '41008',
		direccion: 'ARROYO, 105',
		entidad_email: 'm.sanchez.028@recol.es',
		entidad_nif: null,
		entidad_telefono: '954412409',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'SANCHEZ REYES, MATILDE',
		nomentidad_cbim: 'SANCHEZ REYES, MATILDE',
		poblacion: 'SEVILLA',
		provincia: 'SEVILLA',
		sanibrick: 'S410940',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1297,
		coddelegado: 6199,
		codentidad_cbim: 1297,
		codigo_postal: '44002',
		direccion: 'PZ PLAYA DE ARO, 2',
		entidad_email: 'farmaciaealcala@gmail.com',
		entidad_nif: '18411222K',
		entidad_telefono: '978621550',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'ALCALA ESCRICHE, ELISA',
		nomentidad_cbim: 'ALCALA ESCRICHE, ELISA',
		poblacion: 'TERUEL',
		provincia: 'TERUEL',
		sanibrick: 'S440290',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1305,
		coddelegado: 4081,
		codentidad_cbim: 1305,
		codigo_postal: '11201',
		direccion: 'PZ NUESTRA SEÑORA DE LA PALMA, 9',
		entidad_email: null,
		entidad_nif: null,
		entidad_telefono: '956650703',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'FARMACIA ALCALA, C.B.',
		nomentidad_cbim: 'FARMACIA ALCALA, C.B.',
		poblacion: 'ALGECIRAS',
		provincia: 'CADIZ',
		sanibrick: 'S110020',
		tipo: 'FARMACIA',
	},
	{
		codcli_cbim: 1306,
		coddelegado: 4026,
		codentidad_cbim: 1306,
		codigo_postal: '18320',
		direccion: 'PINTOR VELAZQUEZ, 5',
		entidad_email: 'farmaciajanson@gmail.com',
		entidad_nif: '74693304e',
		entidad_telefono: '958440703',
		ind_esfarmacia: true,
		nombre_delegado: null,
		nomcli_cbim: 'JANSON FERNANDEZ, SILVIA MARION',
		nomentidad_cbim: 'JANSON FERNANDEZ, SILVIA MARION',
		poblacion: 'SANTAFE',
		provincia: 'GRANADA',
		sanibrick: 'S180580',
		tipo: 'FARMACIA',
	},
]
