export const NEW_GROUP = 'NEW_GROUP'
export const EDIT_GROUP = 'EDIT_GROUP'
export const ELIMINAR_DEPENDENCIAS = 'ELIMINAR_DEPENDENCIAS'
export const SHOWMODAL_GRUPO_SUCCESS = 'SHOWMODAL_GRUPO_SUCCESS'

