export const FETCH_SALES_BY_YEAR = 'FETCH_SALES_BY_YEAR'; 
export const FETCH_SALES_BY_MONTH = 'FETCH_SALES_BY_MONTH';
export const FETCH_SALES_BY_DAY = 'FETCH_SALES_BY_DAY'; 
export const FETCH_SALES_BY_HOUR = 'FETCH_SALES_BY_HOUR';
export const FETCH_SALES_BY_YEAR_SUCCESS = 'FETCH_SALES_BY_YEAR_SUCCESS';
export const FETCH_SALES_BY_MONTH_SUCCESS = 'FETCH_SALES_BY_MONTH_SUCCESS';
export const FETCH_SALES_BY_DAY_SUCCESS = 'FETCH_SALES_BY_DAY_SUCCESS'; 
export const FETCH_SALES_BY_HOUR_SUCCESS= 'FETCH_SALES_BY_HOUR_SUCCESS';
export const FETCH_ENTITIES_SUCCESS= 'FETCH_ENTITIES_SUCCESS';
export const FETCH_SUBFAMILY_SUCCESS= 'FETCH_SUBFAMILY_SUCCESS';
export const FETCH_CLIENTS_DATA = 'FETCH_CLIENTS_DATA';
export const FETCH_CLIENTS_DATA_SUCCESS = 'FETCH_CLIENTS_DATA_SUCCESS';
export const FETCH_CLIENTS_SALES_SUCCESS = 'FETCH_CLIENTS_SALES_SUCCESS';
export const FETCH_CLIENTS_ACTIVITY_SUCCESS = 'FETCH_CLIENTS_ACTIVITY_SUCCESS';
export const FETCH_PENDING_TASKS = 'FETCH_PENDING_TASKS';
export const FETCH_PENDING_TASKS_SUCCESS = 'FETCH_PENDING_TASKS_SUCCESS';
export const FETCH_SALES_YEAR_DAYS_SUCCESS = 'FETCH_SALES_YEAR_DAYS_SUCCESS';
export const FETCH_SALES_BY_HOUR_FAIL = 'FETCH_SALES_BY_HOUR_FAIL';
export const FETCH_SUBFAMILY_YEAR_SUCCESS = 'FETCH_SUBFAMILY_YEAR_SUCCESS';
export const FETCH_SUBFAMILY_MONTH_SUCCESS = 'FETCH_SUBFAMILY_MONTH_SUCCESS';
export const FETCH_SUBFAMILY_DAY_SUCCESS = 'FETCH_SUBFAMILY_DAY_SUCCESS';
export const FETCH_SUBFAMILY_HOUR_SUCCESS = 'FETCH_SUBFAMILY_HOUR_SUCCESS';
export const FETCH_ENTITIES_YEAR_SUCCESS= 'FETCH_ENTITIES_YEAR_SUCCESS';
export const FETCH_ENTITIES_YEAR_ACTIVES_SUCCESS = 'FETCH_ENTITIES_YEAR_ACTIVES_SUCCESS';

  



