export const STATUS = {
    NOT_FETCHED_LINE_CHART: 'not-feched-line-chart',
    FETCHING_LINE_CHART: 'fetching-line-chart',
    FETCHED_LINE_CHART: 'fetched-line-chart',
    FETCHED_FAIL_LINE_CHART: 'fetched-fail-line-chart', 
    NOT_FETCHED_CLIENTS: 'not-feched-clients',
    FETCHING_CLIENTS: 'fetching-clients',
    FETCHED_CLIENTS: 'fetched-clients',
    FETCHED_FAIL_CLIENTS: 'fetched-fail-clients', 
    FETCHED_SUBFAMILIES_CHART: 'fetched-subfamilies-chart',
    NOT_FETCHED_SUBFAMILIES_CHART: 'not-feched-subfamilies-chart',
    FETCHING_SUBFAMILIES_CHART: 'fetching-subfamilies-chart',
    FETCHED_FAIL_SUBFAMILIES_CHART: 'fetched-fail-subfamilies-chart', 
    FETCHED_CLIENTS_ACTIVES_CHART: 'fetched-clients-actives-chart',
    NOT_FETCHED_CLIENTS_ACTIVES_CHART: 'not-feched-clients-actives-chart',
    FETCHING_CLIENTS_ACTIVES_CHART: 'fetching-clients-actives-chart',
    FETCHED_FAIL_CLIENTS_ACTIVES_CHART: 'fetched-fail-clients-actives-chart', 
    NOT_FETCHED_CLIENTS_INACTIVES_CHART: 'not-fetched-clients-inactives-chart',
    FETCHED_CLIENTS_INACTIVES_CHART: 'fetched-clients-inactives-chart',
    FETCHING_CLIENTS_INACTIVES_CHART: 'fetching-clients-inactives-chart',
    FETCHED_FAIL_CLIENTS_INACTIVES_CHART: 'fetched-fail-clients-inactives-chart',
  };
  
