export const LOAD_MENU_ITEMS = 'LOAD_MENU_ITEMS';
export const LOAD_MENU_ITEMS_SUCCESS = 'LOAD_MENU_ITEMS_SUCCESS';
export const LOAD_MENU_ITEMS_FAILED = 'LOAD_MENU_ITEMS_FAILED';
export const SELECT_PARENT_ITEM = 'SELECT_PARENT_ITEM';
export const LOAD_CHILD_ITEMS_MENU = 'LOAD_CHILD_ITEMS_MENU';
export const LOAD_CHILD_ITEMS_MENU_SUCCESS= 'LOAD_CHILD_ITEMS_MENU_SUCCESS';
export const LOAD_CHILD_ITEMS_MENU_FAILED = 'LOAD_CHILD_ITEMS_MENU_FAILED';
export const SET_COLLAPSE = "SET_COLLAPSE";

