export const LOAD_COMMERCIAL_DEALS = 'LOAD_COMMERCIAL_DEALS';
export const LOAD_COMMERCIAL_DEALS_SUCCESS = 'LOAD_COMMERCIAL_DEALS_SUCCESS';
export const LOAD_COMMERCIAL_DEALS_FAILED = 'LOAD_COMMERCIAL_DEALS_FAILED';
export const CREATE_COMMERCIAL_DEAL = 'CREATE_COMMERCIAL_DEAL';
export const CREATE_COMMERCIAL_DEAL_SUCCESS = 'CREATE_COMMERCIAL_DEAL_SUCCESS';
export const CREATE_COMMERCIAL_DEAL_FAILED = 'CREATE_COMMERCIAL_DEAL_FAILED';

//Families
export const LOAD_FAMILIES = 'LOAD_FAMILIES';
export const LOAD_FAMILIES_SUCCESS = 'LOAD_FAMILIES_SUCCESS';
export const LOAD_FAMILIES_FAILED = 'LOAD_FAMILIES_FAILED';

//sub Families
export const LOAD_SUB_FAMILIES = 'LOAD_SUB_FAMILIES';
export const LOAD_SUB_FAMILIES_SUCCESS = 'LOAD_SUB_FAMILIES_SUCCESS';
export const LOAD_SUB_FAMILIES_FAILED = 'LOAD_SUB_FAMILIES_FAILED';

//Products
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const LOAD_PRODUCTS_FAILED = 'LOAD_PRODUCTS_FAILED';

//Brands
export const LOAD_BRANDS = 'LOAD_BRANDS';
export const LOAD_BRANDS_SUCCESS = 'LOAD_BRANDS_SUCCESS';
export const LOAD_BRANDS_FAILED = 'LOAD_BRANDS_FAILED';

//sub brands
export const LOAD_SUB_BRANDS = 'LOAD_SUB_BRANDS';
export const LOAD_SUB_BRANDS_SUCCESS = 'LOAD_SUB_BRANDS_SUCCESS';
export const LOAD_SUB_BRANDS_FAILED = 'LOAD_SUB_BRANDS_FAILED';

//Users
export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_FAILED = 'LOAD_USERS_FAILED';

//commercial deal types
export const LOAD_DEAL_TYPES = 'LOAD_DEAL_TYPES';
export const LOAD_DEAL_TYPES_SUCCESS = 'LOAD_DEAL_TYPES_SUCCESS';
export const LOAD_DEAL_TYPES_FAILED = 'LOAD_DEAL_TYPES_FAILED';

//Forms
export const SHOW_NEW_COMMERCIAL_DEAL = 'SHOW_NEW_COMMERCIAL_DEAL';
export const SHOW_EDIT_COMMERCIAL_DEAL = 'SHOW_EDIT_COMMERCIAL_DEAL';
export const SHOW_VIEW_PRODUCTS_COMMERCIAL_DEAL = 'SHOW_VIEW_PRODUCTS_COMMERCIAL_DEAL';
export const SHOW_NEW_PRODUCT_COMMERCIAL_DEAL = 'SHOW_NEW_PRODUCT_COMMERCIAL_DEAL';
export const SET_CURRENT_COMMERCIAL_DEAL= 'SET_CURRENT_COMMERCIAL_DEAL';
export const UPDATE_PRODUCTS_FILTER = 'UPDATE_PRODUCTS_FILTER';
export const UPDATE_CLIENTS_FILTER = 'UPDATE_CLIENTS_FILTER';



