export const LOAD_COMMERCIAL_DEALS = 'LOAD_COMMERCIAL_DEALS';
export const LOAD_COMMERCIAL_DEALS_SUCCESS = 'LOAD_COMMERCIAL_DEALS_SUCCESS';
export const LOAD_COMMERCIAL_DEALS_FAILED = 'LOAD_COMMERCIAL_DEALS_FAILED';
