export const LOAD_COMMERCIAL_DEALS = 'LOAD_COMMERCIAL_DEALS';
export const LOAD_COMMERCIAL_DEALS_SUCCESS = 'LOAD_COMMERCIAL_DEALS_SUCCESS';
export const LOAD_COMMERCIAL_DEALS_FAILED = 'LOAD_COMMERCIAL_DEALS_FAILED';

//Offers
export const LOAD_OFFERS = 'LOAD_OFFERS';
export const LOAD_OFFERS_SUCCESS = 'LOAD_OFFERS_SUCCESS';
export const LOAD_OFFERS_FAILED = 'LOAD_OFFERS_FAILED';

//Agreements
export const LOAD_AGREEMENTS = 'LOAD_AGREEMENTS';
export const LOAD_AGREEMENTS_SUCCESS = 'LOAD_AGREEMENTS_SUCCESS';
export const LOAD_AGREEMENTS_FAILED = 'LOAD_AGREEMENTS_FAILED';

//Plans
export const LOAD_PLANS = 'LOAD_PLANS';
export const LOAD_PLANS_SUCCESS = 'LOAD_PLANS_SUCCESS';
export const LOAD_PLANS_FAILED = 'LOAD_PLANS_FAILED';

//Campaings
export const LOAD_CAMPAIGNS = 'LOAD_CAMPAIGNS';
export const LOAD_CAMPAIGNS_SUCCESS = 'LOAD_CAMPAIGNS_SUCCESS';
export const LOAD_CAMPAIGNS_FAILED = 'LOAD_CAMPAIGNS_FAILED';

