import * as Yup from 'yup';

export const formData = [
	{name:"codcli_cbim",     type:"Integer", validation:undefined},
	{name:"nomcli_cbim",     type:"String", validation:undefined},
	{name:"idpedido",        type:"Integer", validation:undefined},
	{name:"origen",          type:"String", validation:undefined},
	{name:"fecha_alta",      type:"Date", validation:undefined},
	{name:"codentidad_cbim", type:"Integer", validation:undefined},
	{name:"nomentidad_cbim", type:"String", validation:undefined},
	{name:"codestado",       type:"String", validation:undefined},
	{name:"nomestado",       type:"String", validation:undefined},
	{name:"codcompañia",     type:"Integer", validation:undefined},
	{name:"codmayorista",    type:"Integer", validation:undefined},
	{name:"nommayorista",    type:"String", validation:undefined},
	{name:"incidencia",      type:"String", validation:undefined},
];

export const tableCols = [
	{ title: "Item",
		key: "index", 
		align: "center",
		render: (text, record, index) => index + 1,
	},
	{ title: "Cód INDAS",
		dataIndex: "codindas",
		key: "codindas", 
		align: "center",
	},
	{ title: "Producto",
		dataIndex: "nomproducto",
		key: "nomproducto", 
		ellipsis: true,
	},
	{ title: "Unidades",
		dataIndex: "cantidad",
		key: "cantidad", 
		align: "center",
		editable: true,
	},
	{ title: "Dto (%)",
		dataIndex: "descuento",
		key: "descuento", 
		align: "center",
		render: (text) => text + ' %',
		editable: true,
	},
	{ title: "Puntos",
		dataIndex: "puntos",
		key: "puntos", 
		align: "center",
		editable: true,
	}
];

export const values = {
  "codcli_cbim": 111111,
  "nomcli_cbim": "Nombre del cliente en CBIM",
  "idpedido": 999999,
	"origen": "NTR",
  "fecha_alta": "11/01/2019",
  "codentidad_cbim": 2222,
  "nomentidad_cbim": "Nombre de la entidad en CBIM",
  "codestado": "valiating",
  "nomestado": "En revisión",
  "codcompañia": "xxxxxxx",
  "codmayorista": 1,
  "indicencia": "Descripción de la incidencia",
  "lineas": [
    {"codindas": 2820001,
     "nomproducto": "Nombre del producto 1",
     "cantidad": 12,
     "descuento": 10,
     "puntos": 0},
    {"codindas": 2820002,
     "nomproducto": "Nombre del producto 2",
     "cantidad": 1,
     "descuento": 20,
     "puntos": 2},
    {"codindas": 2820003,
     "nomproducto": "Nombre del producto 3",
     "cantidad": 14,
     "descuento": 20,
     "puntos": 2},
    {"codindas": 2820004,
     "nomproducto": "Nombre del producto 4",
     "cantidad": 11,
     "descuento": 10,
     "puntos": 2},
    {"codindas": 2820006,
     "nomproducto": "Nombre del producto 6",
     "cantidad": 1,
     "descuento": 5,
     "puntos": 0},
  ],
	"mayoristas": [
		{ "codmayorista": 1,
		 "nombre": "Mayorista 1" },
		{ "codmayorista": 2,
		 "nombre": "Mayorista 2" },
		{ "codmayorista": 3,
		 "nombre": "Mayorista 3" },
		{ "codmayorista": 4,
		 "nombre": "Mayorista 4" },
		{ "codmayorista": 5,
		 "nombre": "Mayorista 5" },
	]
}
