export const FETCH_PLANS = 'FETCH_PLANS';
export const FETCH_PLANS_SUCCESS = 'FETCH_PLANS_SUCCESS';
export const FETCH_PLANS_COUNT_SUCCESS = 'FETCH_PLANS_COUNT_SUCCESS';
export const FETCH_PLANS_FAILED = 'FETCH_PLANS_FAILED';
export const FETCH_PLANS_LOADING = 'FETCH_PLANS_LOADING';
export const CREATE_PLAN = 'CREATE_PLAN';
export const CREATE_PLAN_SUCCESS = 'CREATE_PLAN_SUCCESS';
export const CREATE_PLAN_FAILED = 'CREATE_PLAN_FAILED';
export const CREATE_PLAN_SET_LOADING = 'CREATE_PLAN_SET_LOADING';
export const FETCH_DELEGADOS = 'FETCH_DELEGADOS';
export const FETCH_DELEGADOS_SUCCESS = 'FETCH_DELEGADOS_SUCCESS';
export const FETCH_DELEGADOS_FAILED = 'FETCH_DELEGADOS_FAILED';

export const FETCH_SUBMARCA_COLLECTIONS = 'FETCH_SUBMARCA_COLLECTIONS';
export const FETCH_SUBMARCA_COLLECTIONS_SUCCESS = 'FETCH_SUBMARCA_COLLECTIONS_SUCCESS';
export const FETCH_SUBMARCA_COLLECTIONS_FAILED = 'FETCH_SUBMARCA_COLLECTIONS_FAILED';
export const FETCH_SUBMARCA_COLLECTIONS_LOADING = 'FETCH_SUBMARCA_COLLECTIONS_LOADING';

export const CREATE_SUBMARCA_COLLECTION = 'CREATE_SUBMARCA_COLLECTION';
export const CREATE_SUBMARCA_COLLECTION_SUCCESS = 'CREATE_SUBMARCA_COLLECTION_SUCCESS';
export const CREATE_SUBMARCA_COLLECTION_FAILED = 'CREATE_SUBMARCA_COLLECTION_FAILED';
export const CREATE_SUBMARCA_COLLECTION_SET_LOADING = 'CREATE_SUBMARCA_COLLECTION_SET_LOADING';

export const UPDATE_PLAN = 'UPDATE_PLAN';
export const UPDATE_PLAN_SUCCESS = 'UPDATE_PLAN_SUCCESS';
export const UPDATE_PLAN_FAILED = 'UPDATE_PLAN_FAILED';

export const UPDATE_PLANS = 'UPDATE_PLANS';
export const UPDATE_PLANS_SUCCESS = 'UPDATE_PLANS_SUCCESS';

export const FETCH_PLAN = 'FETCH_PLAN';
export const FETCH_PLAN_SUCCESS = 'FETCH_PLAN_SUCCESS';
export const FETCH_PLAN_FAILED = 'FETCH_PLAN_FAILED';

export const SET_FILTERS = 'SET_FILTERS';
