export const FETCH_PLANS = 'FETCH_PLANS';
export const FETCH_PLANS_SUCCESS = 'FETCH_PLANS_SUCCESS';
export const FETCH_PLANS_FAILED = 'FETCH_PLANS_FAILED';
export const FETCH_PLANS_LOADING = 'FETCH_PLANS_LOADING';
