export const LIMIT = 15;

export const pedidos = [
{
    codcupon: null,
    codcli_cbim: 1234,
    codentidad_cbim: 191509,
    codestado: "completed",
    codmayorista: 245,
    drupal_order_id: "401500020575",
    estado: "Tramitado",
    fecha_alta: "1969-12-31T23:00:00+00:00",
    fecha_modif: null,
    idpedido: 87788,
    nombre_mayorista: "BIDAFARMA",
    nomentidad_cbim: "MILLAN OCAÑA, MARIA CRISTINA",
    num_lineas: 1,
    origen: "TR",
    tipo: "Pedidos"

},
{
    codcupon: null,
    codcli_cbim: 1235,
    codentidad_cbim: 191510,
    codestado: "completed",
    codmayorista: 246,
    drupal_order_id: "401500020576",
    estado: "Tramitado",
    fecha_alta: "1969-12-31T23:00:00+00:00",
    fecha_modif: null,
    idpedido: 87789,
    nombre_mayorista: "BIDAFARMA",
    nomentidad_cbim: "MILLAN OCAÑA, MARIA CRISTINA",
    num_lineas: 1,
    origen: "TR",
    tipo: "Pedidos"

},
{
    codcupon: null,
    codcli_cbim: 1236,
    codentidad_cbim: 191511,
    codestado: "completed",
    codmayorista: 247,
    drupal_order_id: "401500020577",
    estado: "Tramitado",
    fecha_alta: "1969-12-31T23:00:00+00:00",
    fecha_modif: null,
    idpedido: 87790,
    nombre_mayorista: "BIDAFARMA",
    nomentidad_cbim: "MILLAN OCAÑA, MARIA CRISTINA",
    num_lineas: 1,
    origen: "TR",
    tipo: "Pedidos"

},
{
    codcupon: null,
    codcli_cbim: 1237,
    codentidad_cbim: 191512,
    codestado: "completed",
    codmayorista: 248,
    drupal_order_id: "401500020578",
    estado: "Tramitado",
    fecha_alta: "1969-12-31T23:00:00+00:00",
    fecha_modif: null,
    idpedido: 87791,
    nombre_mayorista: "BIDAFARMA",
    nomentidad_cbim: "MILLAN OCAÑA, MARIA CRISTINA",
    num_lineas: 1,
    origen: "TR",
    tipo: "Pedidos"

},
{
    codcupon: null,
    codcli_cbim: 1238,
    codentidad_cbim: 191513,
    codestado: "completed",
    codmayorista: 249,
    drupal_order_id: "401500020579",
    estado: "Tramitado",
    fecha_alta: "1969-12-31T23:00:00+00:00",
    fecha_modif: null,
    idpedido: 87792,
    nombre_mayorista: "BIDAFARMA",
    nomentidad_cbim: "MILLAN OCAÑA, MARIA CRISTINA",
    num_lineas: 1,
    origen: "TR",
    tipo: "Pedidos"

},
{
    codcupon: null,
    codcli_cbim: 1239,
    codentidad_cbim: 191514,
    codestado: "completed",
    codmayorista: 250,
    drupal_order_id: "401500020580",
    estado: "Tramitado",
    fecha_alta: "1969-12-31T23:00:00+00:00",
    fecha_modif: null,
    idpedido: 87793,
    nombre_mayorista: "BIDAFARMA",
    nomentidad_cbim: "MILLAN OCAÑA, MARIA CRISTINA",
    num_lineas: 1,
    origen: "TR",
    tipo: "Pedidos"

},

]

export const cliente = {
        apellido1: "ABAURRE",
        apellido2: "MORALES",
        codcli_cbim: 1022,
        email: "farmacia245@cofcordoba.com",
        estado: "Activo",
        fecha_alta: "2008-07-14T00:00:00+02:00",
        fecha_baja: null,
        fecha_modif: null,
        idcliente: 1,
        idestado: 1,
        ind_acepta_emailcomercial: true,
        nif: null,
        nombre: "Julio",
        nomcli_cbim: "MATIULDE",
        telefono: 957601124
      }
            
export const productos = [
    
        {
          codean13: "8410520039176",
          codindas: "2021618",
          codnacional: "153982.3",
          descripcion:"" ,
          descuento1: "",
          descuento2: "",
          idfamilia: 4,
          idgrupo: 3,
          idmarca: 10,
          idsubfamilia: 14,
          idsubmarca: 1,
          imagengrande1: null,
          imagengrande2: null,
          imagengrande3: null,
          imagengrande4: null,
          indactivo: true,
          indcatpuntos: false,
          ocultar_rela: false,
          indsolofarmacia: false,
          nombre: "ADDERMIS BIACTIV Aceite Protector e Hidratante. Envase 100 ml.",
          nombrefamilia: "SISTEMAS PARA PROTECCIÓN E HIGIENE DE LA PIEL",
          nombregrupo: "HIGIENE & PROTECCION",
          nombremarca: "ADDERMIS",
          nombresubfamilia: "PREVENCIÓN DE ULCERACIONES",
          nombresubmarca: "Sin definir",
          puntosacumulado: 0,
          puntoscoste: 0,
          pvl: 430.000000,
          pvm: 0.000000,
          pvp: null
        },
        {
          codean13: "8410520008202",
          codindas: "2021606",
          codnacional: "310995.6",
          descripcion: "",
          descuento1: "",
          descuento2: "",
          idfamilia: 4,
          idgrupo: 3,
          idmarca: 10,
          idsubfamilia: 15,
          idsubmarca: 1,
          imagengrande1: null,
          imagengrande2: null,
          imagengrande3: null,
          imagengrande4: null,
          indactivo: true,
          indcatpuntos: false,
          ocultar_rela: false,
          indsolofarmacia: false,
          nombre: "ADDERMIS BIACTIV Bolsa 60 u. Toallas Húmedas Aseo Intimo",
          nombrefamilia: "SISTEMAS PARA PROTECCIÓN E HIGIENE DE LA PIEL",
          nombregrupo: "HIGIENE & PROTECCION",
          nombremarca: "ADDERMIS",
          nombresubfamilia : "HIGIENE CORPORAL ADULTOS",
          nombresubmarca: "Sin definir",
          puntosacumulado: 0,
          puntoscoste: 0,
          pvl: 398.000000,
          pvm: 0.000000,
          pvp: null
        },

        {
            codean13: "8410520008202",
            codindas: "2021606",
            codnacional: "310995.6",
            descripcion: "",
            descuento1: "",
            descuento2: "",
            idfamilia: 4,
            idgrupo: 3,
            idmarca: 10,
            idsubfamilia: 15,
            idsubmarca: 1,
            imagengrande1: null,
            imagengrande2: null,
            imagengrande3: null,
            imagengrande4: null,
            indactivo: true,
            indcatpuntos: false,
            ocultar_rela: false,
            indsolofarmacia: false,
            nombre: "ADDERMIS BIACTIV Bolsa 60 u. Toallas Húmedas Aseo Intimo",
            nombrefamilia: "SISTEMAS PARA PROTECCIÓN E HIGIENE DE LA PIEL",
            nombregrupo: "HIGIENE & PROTECCION",
            nombremarca: "ADDERMIS",
            nombresubfamilia : "HIGIENE CORPORAL ADULTOS",
            nombresubmarca: "Sin definir",
            puntosacumulado: 0,
            puntoscoste: 0,
            pvl: 398.000000,
            pvm: 0.000000,
            pvp: null
          },
       
      
]